# Generated by Django 3.1.4 on 2020-12-15 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
