# Generated by Django 3.1.4 on 2020-12-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
